---
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
featureGates:
  EndpointSliceTerminatingCondition: true
networking:
  disableDefaultCNI: true
  podSubnet: 10.3.0.0/16
  serviceSubnet: 172.20.3.0/24
  kubeProxyMode: none
nodes:
  - role: control-plane
    kubeadmConfigPatches:
    - |
      apiVersion: kubeadm.k8s.io/v1beta2
      kind: InitConfiguration
      nodeRegistration:
        taints: []
  - role: worker
    extraPortMappings:
    - containerPort: 30009 # deathstar NodePort service
      hostPort: 30009
      listenAddress: "0.0.0.0"
      protocol: tcp
    - containerPort: 30019 # tiefighter NodePort service
      hostPort: 30019
      listenAddress: "0.0.0.0"
      protocol: tcp
    kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "ingress-ready=true"