{
 "title": "Cilium clustermesh",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Cluster 1 pods",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (pod) (rate(tiefighter_requests{cluster=\"Cluster1\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster 2 pods",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum by (pod) (rate(tiefighter_requests{cluster=\"Cluster2\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster 3 pods",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum by (pod) (rate(tiefighter_requests{cluster=\"Cluster3\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Clusters load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum by (cluster) (rate(tiefighter_requests[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "rate(tiefighter_errors[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}