---
apiVersion: v1
kind: Service
metadata:
  name: deathstar
  annotations:
    io.cilium/global-service: "true"
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30009
  selector:
    name: deathstar
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deathstar
spec:
  selector:
    matchLabels:
      name: deathstar
  replicas: 2
  template:
    metadata:
      labels:
        name: deathstar
    spec:
      containers:
        - name: deathstar-container
          image: deathstar:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: RESPONSE_TEMPLATE
              value: '{"cluster": "Cluster3", "pod": "{{ env "K8S_POD_NAME" }}"}'
            - name: RESPONSE_DELAY
              value: 0s
            - name: SIGNAL_REACTION_DELAY
              value: 5s
            - name: K8S_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
      terminationGracePeriodSeconds: 120
---
apiVersion: v1
kind: Service
metadata:
  name: tiefighter
  # annotations:
  #   io.cilium/global-service: "true"
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30019
  selector:
    name: tiefighter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tiefighter
spec:
  selector:
    matchLabels:
      name: tiefighter
  replicas: 1
  template:
    metadata:
      labels:
        name: tiefighter
    spec:
      containers:
      - name: tiefighter-container
        image: tiefighter:latest
        imagePullPolicy: Never
        ports:
         - containerPort: 8080
        args: [
          "--target-addr", "http://deathstar",
          "--listen-addr", ":8080", # metrics
        ]